spring:
  application:
    name: SB03-Otboo-Boolsajo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ID}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
          google:
            client-name: Google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # Spring Actuator
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, loggers
    endpoint:
      info:
        enabled: true
      health:
        show-details: always
    info:
      env:
        enabled: true
      java:
        enabled: true

logging:
  level:
    root: info
    com.sprint.otboo.weather.integration.kma.client: debug

weather:
  kma:
    base-url: https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0/getVilageFcst
    auth-key: ${KMA_AUTH_KEY}
    connect-timeout-ms: 3000
    read-timeout-ms: 5000
    retry-max-attempts: 3
    retry-backoff-ms: 300
    num-of-rows: 400
    data-type: JSON
    enabled: true

kakao:
  api:
    base-url: ${KAKAO_API_BASE_URL}
    rest-api-key: ${KAKAO_REST_API_KEY}
jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:fA7qL8pX9vE3+gH1jZ5rK2cW0uB4dF6yG8iN/oP3tS4=}
    expiration: ${JWT_ACCESS_EXPIRATION:600000}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:zK9bC2dR5uH8xL1mQ4vA7wE3gF6jT0fV/oI2sY5pX9c=}
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  session:
    max-active-jwt: 1

storage:
  local:
    enabled: false
    upload-dir: ${user.home}/otboo/uploads
    base-url: http://localhost:8080/uploads
  s3:
    enabled: true
    bucket: ${S3_BUCKET_NAME:otboo-bucket-boolsajo-deploy}
    base-url: https://s3.ap-northeast-2.amazonaws.com/${S3_BUCKET_NAME:otboo-bucket-boolsajo-deploy}
    region: ap-northeast-2
    prefixes:
      profile: binary-content/profiles
      clothing: binary-content/clothing

# defaultPassword
admin:
  default:
    password: ${ADMIN_DEFAULT_PASSWORD}

es:
  host: ${ELASTICSEARCH_HOST}
  api-key: ${ELASTICSEARCH_API_KEY}