spring:
  application:
    name: SB03-Otboo-Boolsajo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Spring Actuator
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, loggers
    endpoint:
      info:
        enabled: true
      health:
        shwo-details: always
    info:
      env:
        enabled: true
      java:
        enabled: true

logging:
  level:
    root: info

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:fA7qL8pX9vE3+gH1jZ5rK2cW0uB4dF6yG8iN/oP3tS4=}
    expiration: ${JWT_ACCESS_EXPIRATION:600000}