spring:
  application:
    name: SB03-Otboo-Boolsajo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine

  # Spring Actuator
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, loggers
    endpoint:
      info:
        enabled: true
      health:
        shwo-details: always
    info:
      env:
        enabled: true
      java:
        enabled: true

logging:
  level:
    root: info


kakao:
  api:
    base-url: ${KAKAO_API_BASE_URL}
    rest-api-key: ${KAKAO_REST_API_KEY}
jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:fA7qL8pX9vE3+gH1jZ5rK2cW0uB4dF6yG8iN/oP3tS4=}
    expiration: ${JWT_ACCESS_EXPIRATION:600000}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:zK9bC2dR5uH8xL1mQ4vA7wE3gF6jT0fV/oI2sY5pX9c=}
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  session:
    max-active-jwt: 1