spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:phoenixdb}?currentSchema=${POSTGRES_SCHEMA:otboo_schema}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:phoenix}
    password: ${POSTGRES_PASSWORD:phoenix}
    hikari:
      connection-init-sql: SET search_path TO ${POSTGRES_SCHEMA:otboo_schema}, public;
      schema: ${POSTGRES_SCHEMA:otboo_schema}
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${POSTGRES_SCHEMA:otboo_schema}
    show-sql: true
  logging:
    level:
      root: INFO
      com.sprint.otboo: DEBUG
      org.hibernate.SQL: DEBUG
management:
  health:
    redis:
      enabled: false