name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - run: ./gradlew clean build
        env:
          SPRING_PROFILES_ACTIVE: test
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - run: ./gradlew jacocoTestReport
        if: success()

      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
